-- Supabase database สำหรับ SafeReport โรงเรียน
create table if not exists school_reports (
 id bigint generated by default as identity primary key,
 report_type text not null,
 incident_date date not null,
 place text not null,
 description text not null,
 reported_person text,
 image_urls text[] default '{}',
 contact_requested boolean default false,
 contact_info text,
 status text not null default 'รอตรวจสอบ',
 created_at timestamptz not null default now()
);

alter table school_reports enable row level security;

-- ผู้ใช้งานทั่วไปส่งรายงานได้ แต่ไม่ควรอ่านข้อมูลของคนอื่น
create policy "public can submit report"
on school_reports for insert to anon
with check (true);

-- ให้เฉพาะบัญชีผู้ดูแลที่ผ่าน Authentication อ่าน/แก้ไข/ลบ
create policy "admin can read reports"
on school_reports for select to authenticated using (true);

create policy "admin can update reports"
on school_reports for update to authenticated using (true) with check (true);

create policy "admin can delete reports"
on school_reports for delete to authenticated using (true);
